### ISSUE TITLE
#TK06 - Pagina Nosotros

### ISSUE THREAD

**Issue by CarlosVecchi** [ovejerojose/Full_Stack#33]
Realizar la pagina Nosotros  con los datos de los integrantes del proyecto y se podria subir los CV de cada uno

**Comment by Lusosa** [comment]
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/estilos.css">
    <title>ISPC Tennis Court</title>
</head>
<body>
    <header>

        <center>
            <nav>
                <ul class="nav-links">

                    <li class="nav-item">
                        <a class="nav-link" href="Index.html">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="nosotros.html">Nosotros</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Servicios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="#">Registro</a>
                    </li>
                </ul>
        </center>
    </header>
    <header>
        <center> <H1> Somos estudiantes del ISPC </H1></center>

    </header>


    <div class="columna">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <body>

            <div class="w3-container">

                <div class="w3-card-4" style="width:100%">
                    <img src="imagenes/JoseOviedo.jpg" alt="JoseOviedo" style="width:100%">
                    <div class="w3-container w3-center">
                        <h4>Jose Oviedo</h4>
                        <p>
                            Estudiante de
                            la tecnicatura
                            Desarrollo Web
                            y Aplicaciones -->
                            <a class="nav-link" href="https://github.com/JosePolvora">GITHUB</a>

                        </p>
                    </div>
                </div>
            </div>

        </body>



        <div class="w3-container">

            <div class="w3-card-4" style="width:100%">
                <img src="imagenes/LuSosa.jpg" alt="LucianaSosa" style="width:100%">
                <div class="w3-container w3-center">
                    <h4>Luciana Sosa</h4>
                    <p>
                        Estudiante de
                        la tecnicatura
                        Desarrollo Web
                        y Aplicaciones -->
                        <a class="nav-link" href="https://github.com/Lusosa">GITHUB</a>

                    </p>
                </div>
            </div>
        </div>

        <div class="w3-container">

            <div class="w3-card-4" style="width:100%">
                <img src="imagenes/SaraOlivera.jpg" alt="SaraOlivera" style="width:100%">
                <div class="w3-container w3-center">
                    <h4> Sara Olivera</h4>
                    <p>
                        Estudiante de
                        la tecnicatura
                        Desarrollo Web
                        y Aplicaciones -->
                        <a class="nav-link" href="https://github.com/SaraEOlivera">GITHUB</a>

                    </p>
                </div>
            </div>
        </div>


        <div class="w3-container">

            <div class="w3-card-4" style="width:100%">
                <img src="imagenes/GermanZamudio.jpg" alt="GermanZamudio" style="width:100%">
                <div class="w3-container w3-center">
                    <h4>German Zamudio</h4>
                        <p>
                            Estudiante de
                            la tecnicatura
                            Desarrollo Web
                            y Aplicaciones -->
                            <a class="nav-link" href="https://github.com/GermanZamudio">GITHUB</a>

                        </p>
                </div>
            </div>
        </div>


        <div class="w3-container">

            <div class="w3-card-4" style="width:100%">
                <img src="imagenes/CarlosVecchi.jpg" alt="CarlosVecchi" style="width:100%">
                <div class="w3-container w3-center">
                    <h4>Carlos Vecchi</h4>
                    <p>
                        Estudiante de
                        la tecnicatura
                        Desarrollo Web
                        y Aplicaciones -->
                        <a class="nav-link" href="https://github.com/CarlosVecchi">GITHUB</a>

                    </p>
                </div>
            </div>
        </div>

        <div class="w3-container">

            <div class="w3-card-4" style="width:100%">
                <img src="imagenes/ArielOrtiz.jpg" alt="ArielOrtiz" style="width:100%">
                <div class="w3-container w3-center">
                    <h4>Ariel <br /> Ortiz</h4>
                    <p>
                        Estudiante de
                        la tecnicatura
                        Desarrollo Web
                        y Aplicaciones -->
                        <a class="nav-link" href="https://github.com/ariel957">GITHUB</a>

                    </p>
                </div>
            </div>
        </div>
        <div class="w3-container">

            <div class="w3-card-4" style="width:100%">
                <img src="imagenes/SaraOlivera.jpg" alt="ElizabethFlores" style="width:100%">
                <div class="w3-container w3-center">
                    <h4>Elizabeth Flores</h4>
                    <p>
                        Estudiante de
                        la tecnicatura
                        Desarrollo Web
                        y Aplicaciones -->
                        <a class="nav-link" href="https://github.com/elizabethf3">GITHUB</a>

                    </p>
                </div>
            </div>
        </div>

        <div class="w3-container">

            <div class="w3-card-4" style="width:100%">
                <img src="imagenes/JoseOvejero.jpg" alt="JoseOvejero" style="width:100%">
                <div class="w3-container w3-center">
                    <h4>Jose Ovejero</h4>
                    <p>
                        Estudiante de
                        la tecnicatura
                        Desarrollo Web
                        y Aplicaciones -->
                        <a class="nav-link" href="https://github.com/ovejerojose">GITHUB</a>

                    </p>
                </div>
            </div>
        </div>

    </div>


     
            <center><p style="text-align: center;" class="ef3d">ALQUILER DE CANCHAS SA</p></center>
            

</body>
</html>
